/*
 JavaScript tracking client

 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license https://opensource.org/licenses/BSD-3-Clause BSD-3 Clause (also in js/LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
*/
(function(){function O(a){"@babel/helpers - typeof";return O="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"==typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c},O(a)}function I(a){console.error(a)}function md(){if(jc)return wb.exports;jc=1;(function(a,c){(function(e,g){a.exports=g()})(kc,function(){function e(r){return r.charAt(0).toUpperCase()+r.substring(1)}function g(r){return function(){return this[r]}}
function h(r){if(r)for(var q=0;q<u.length;q++)if(void 0!==r[u[q]])this["set"+e(u[q])](r[u[q]])}var n=["isConstructor","isEval","isNative","isToplevel"],m=["columnNumber","lineNumber"],p=["fileName","functionName","source"],u=n.concat(m,p,["args"],["evalOrigin"]);h.prototype={getArgs:function(){return this.args},setArgs:function(r){if("[object Array]"!==Object.prototype.toString.call(r))throw new TypeError("Args must be an Array");this.args=r},getEvalOrigin:function(){return this.evalOrigin},setEvalOrigin:function(r){if(r instanceof
h)this.evalOrigin=r;else if(r instanceof Object)this.evalOrigin=new h(r);else throw new TypeError("Eval Origin must be an Object or StackFrame");},toString:function(){var r=this.getFileName()||"",q=this.getLineNumber()||"",E=this.getColumnNumber()||"",K=this.getFunctionName()||"";return this.getIsEval()?r?"[eval] ("+r+":"+q+":"+E+")":"[eval]:"+q+":"+E:K?K+" ("+r+":"+q+":"+E+")":r+":"+q+":"+E}};h.fromString=function(r){var q=r.indexOf("("),E=r.lastIndexOf(")"),K=r.substring(0,q);q=r.substring(q+1,
E).split(",");r=r.substring(E+1);if(0===r.indexOf("@")){var J=/@(.+?)(?::(\d+))?(?::(\d+))?$/.exec(r,""),V=J[1],H=J[2];J=J[3]}return new h({functionName:K,args:q||void 0,fileName:V,lineNumber:H||void 0,columnNumber:J||void 0})};for(var v=0;v<n.length;v++)h.prototype["get"+e(n[v])]=g(n[v]),h.prototype["set"+e(n[v])]=function(r){return function(q){this[r]=!!q}}(n[v]);for(n=0;n<m.length;n++)h.prototype["get"+e(m[n])]=g(m[n]),h.prototype["set"+e(m[n])]=function(r){return function(q){if(isNaN(parseFloat(q))||
!isFinite(q))throw new TypeError(r+" must be a Number");this[r]=Number(q)}}(m[n]);for(m=0;m<p.length;m++)h.prototype["get"+e(p[m])]=g(p[m]),h.prototype["set"+e(p[m])]=function(r){return function(q){this[r]=String(q)}}(p[m]);return h})})(wb);return wb.exports}function Na(a){var c=/^(?:(?:https?|ftp):)\/*(?:[^@?]+@)?([^:/#]+)/.exec(a);return c?c[1]:a}function lc(a){var c=document.createElement("a");c.href=a;return{href:c.href,hostname:c.hostname,pathname:c.pathname}}function mc(a,c){a=String(a);if(-1===
a.indexOf("?"+c+"=")&&-1===a.indexOf("&"+c+"="))return a;var e=a.indexOf("?");if(-1===e)return a;var g=a.substr(e+1);e=a.substr(0,e);if(g){var h="",n=g.indexOf("#");-1!==n&&(h=g.substr(n+1),g=g.substr(0,n));n=g.split("&");for(var m=n.length-1;0<=m;m--)g=n[m].split("=")[0],g===c&&n.splice(m,1);(g=n.join("&"))&&(e=e+"?"+g);h&&(e+="#"+h)}return e}function nc(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function xb(a,c){a=String(a).toLowerCase();c=String(c).toLowerCase();if(a===c)return!0;if("."===c.slice(0,
1)){if(a===c.slice(1))return!0;var e=a.length-c.length;if(0<e&&a.slice(e)===c)return!0}return!1}function Ya(a,c){var e=document.createElement("a");0!==a.indexOf("//")&&0!==a.indexOf("http")&&(0===a.indexOf("*")&&(a=a.substr(1)),0===a.indexOf(".")&&(a=a.substr(1)),a="http://"+a);e.href=c.toAbsoluteUrl(a);return e.pathname?e.pathname:""}function Za(a,c){return c&&a&&0===String(a).indexOf(c)}function yb(a,c){var e=(new RegExp("[\\?&#]"+c+"=([^&#]*)")).exec(a);return e?decodeURIComponent(e[1]):""}function $a(a,
c){a=mc(a,c.visitorIdUrlParameter);return c.discardHashTag?a.replace(/#.*/,""):a}function w(a){return"undefined"!==typeof a}function ab(a){return"function"===typeof a}function qa(a){return"object"===O(a)}function P(a){return"string"===typeof a||a instanceof String}function za(a){return"number"===typeof a||P(a)&&!isNaN(a)&&""!==a}function Oa(a){var c=a.length;"."===a.charAt(--c)&&(a=a.slice(0,c));"*."===a.slice(0,2)&&(a=a.slice(1));-1!==a.indexOf("/")&&(a=a.substr(0,a.indexOf("/")));return a}function nd(a,
c,e){a||(a="");c||(c="");if("translate.googleusercontent.com"===a)""===e&&(e=c),c=yb(c,"u"),a=Na(c);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))c=document.links[0].href,a=Na(c);return[a,c,e]}function ea(a,c){if(a&&a.indexOf)return a.indexOf(c);if(!w(a)||null===a||0===a.length)return-1;for(var e=0;e<a.length;){if(a[e]===c)return e;e++}return-1}function oc(a){if(a)return!w(a.children)&&w(a.childNodes)||w(a.children)?a.children:[]}function zb(a){var c;for(c=
a.parentNode;null!==c&&w(c)&&!t.isLinkElement(a);)a=c,c=a.parentNode;return a}function Ab(a,c){a=String(a);return 0===a.lastIndexOf(c,0)}function Aa(a,c){a=String(a);return-1!==a.indexOf(c,a.length-c.length)}function pc(a,c){c=String(c);a=String(a);return""!==a?a+c.charAt(0).toUpperCase()+c.slice(1):c}function qc(a,c){a=String(a);return a.substr(0,a.length-c)}function Bb(a,c){var e="(^| )(piwik[_-]"+c;if(a)for(var g=0;g<a.length;g++)e+="|"+a[g];return new RegExp(e+")( |$)")}function od(a,c){var e=
t.getAttributeValueFromNode(a,"href");if(!e)return!1;var g=e.split("://");if(2!==g.length)return!1;e=g[0].toLowerCase();g=g[1];var h=g.indexOf("?");g=-1===h?g:g.slice(0,h);h=[];for(var n=0;n<c.length;n++){var m=c[n];pd.test(m)&&h.push(m)}for(n=0;n<h.length;n++){var p=h[n].split("://");if(2!==p.length)break;m=p[0].toLowerCase();p=p[1];if(e===m&&rc(g,p))return!0}return!1}function rc(a,c){Ab(c,"/")||(c="/"+c);Ab(a,"/")||(a="/"+a);if("/"===c||"/*"===c||a===c)return!0;c=String(c).toLowerCase();a=String(a).toLowerCase();
if(Aa(c,"*"))return(c=c.slice(0,-1))&&"/"!==c&&a!==c?0===a.indexOf(c):!0;Aa(a,"/")||(a+="/");Aa(c,"/")||(c+="/");return 0===a.indexOf(c)}function sc(a,c,e,g){for(var h=0;h<e.length;h++){var n=Oa(e[h]),m=Ya(e[h],g);if(xb(a,n)&&rc(c,m))return!0}return!1}function tc(a,c,e){a=zb(a);if(t.hasNodeAttribute(a,"href")&&w(a.href)){var g=t.getAttributeValueFromNode(a,"href");if(!Za(g,e.configTrackerUrl)){var h=lc(g),n=h.pathname||Ya(g,c);g=h.hostname||Na(h.href);var m=g.toLowerCase();h=h.href.replace(g,m);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto|tel|data|blob):/i.test(h)&&
(g=a.className,c=sc(m,n,e.configHostsAlias,c),a=t.hasNodeAttribute(a,"download"),Za(h,e.configTrackerUrl)?e=0:(n=Bb(e.configDownloadClasses,"download"),m=Bb(e.configLinkClasses,"link"),e=new RegExp("\\.("+e.configDownloadExtensions.join("|")+")([?&#]|$)","i"),e=m.test(g)?"link":a||n.test(g)||e.test(h)?"download":c?0:"link"),e))return{type:e,href:h}}}}function qd(){var a=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;if(null!==a&&void 0!==a&&a.timing)return a.timing;
if(null!==a&&void 0!==a&&a.getEntriesByType)return a.getEntriesByType("navigation")[0]}function Q(a,c,e){return 0<=c&&c<=e?"&"+a+"="+c:""}function R(a,c){return Math.round(a[c]-(a.navigationStart||0))}function rd(a){var c="";a.unloadEventStart&&0!==a.unloadEventStart&&(c+=Q("t_us",R(a,"unloadEventStart"),65535));a.unloadEventEnd&&0!==a.unloadEventEnd&&(c+=Q("t_ue",R(a,"unloadEventEnd"),65535));a.redirectStart&&0!==a.redirectStart&&(c+=Q("t_rs",R(a,"redirectStart"),65535));a.redirectEnd&&0!==a.redirectEnd&&
(c+=Q("t_re",R(a,"redirectEnd"),65535));a.secureConnectionStart&&0!==a.secureConnectionStart&&(c+=Q("t_ss",R(a,"secureConnectionStart"),65535));a.fetchStart&&0!==a.fetchStart&&(c+=Q("t_fs",R(a,"fetchStart"),65535));a.domainLookupStart&&0!==a.domainLookupStart&&(c+=Q("t_ds",R(a,"domainLookupStart"),65535));a.connectStart&&0!==a.connectStart&&(c+=Q("t_cs",R(a,"connectStart"),65535));a.connectEnd&&0!==a.connectEnd&&(c+=Q("t_ce",R(a,"connectEnd"),65535));a.requestStart&&0!==a.requestStart&&(c+=Q("t_qs",
R(a,"requestStart"),65535));a.responseStart&&0!==a.responseStart&&(c+=Q("t_as",R(a,"responseStart"),65535));a.responseEnd&&0!==a.responseEnd&&(c+=Q("t_ae",R(a,"responseEnd"),65535));a.domLoading&&0!==a.domLoading&&(c+=Q("t_dl",R(a,"domLoading"),65535));a.domInteractive&&0!==a.domInteractive&&(c+=Q("t_di",R(a,"domInteractive"),16777215));a.domContentLoadedEventStart&&0!==a.domContentLoadedEventStart&&(c+=Q("t_ls",R(a,"domContentLoadedEventStart"),16777215));a.domContentLoadedEventEnd&&0!==a.domContentLoadedEventEnd&&
(c+=Q("t_le",R(a,"domContentLoadedEventEnd"),16777215));a.domComplete&&0!==a.domComplete&&(c+=Q("t_dc",R(a,"domComplete"),16777215));a.loadEventEnd&&0!==a.loadEventEnd&&(c+=Q("t_ee",R(a,"loadEventEnd"),16777215));return c}function sd(a){var c,e="loading",g=void 0;if(null!==(c=navigator.userAgentData)&&void 0!==c&&c.getHighEntropyValues)navigator.userAgentData.getHighEntropyValues(["model","brands","platform","platformVersion","fullVersionList"]).then(function(h){g=h;e="available"})["catch"](function(h){I(h);
e="unavailable"})["finally"](function(){a.onResolve()});else e="unavailable";return{getState:function(){return"available"===e?{state:"available",hints:g}:{state:e}}}}function uc(a){if(!(a instanceof Array))return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' parameter if specified, has to be array of numbers. Received: '".concat(a,"'")};if(0===a.length)return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' cannot be empty array"};for(var c=0;c<a.length;c++)if("number"!==typeof a[c])return{isValid:!1,
error:"[enableHeartBeatTimer] - 'timers' array has to contain only numeric values. Received: '".concat(a,"'")};return{isValid:!0}}function td(a){var c=!1,e=!1,g=!0,h=vc,n,m=0,p=function q(){var E=h[m];n=void 0===E?void 0:setTimeout(function(){if(g)a.onPing(ra.PeriodicHeartbeat);m++;q()},1E3*E)},u=function(){e&&(p(),e=!1);g||(g=!0,a.onPing(ra.PeriodicHeartbeat))},v=function(){g=!1;a.onPing(ra.BlurHeartbeat)};return{enable:function(){c=!0;window.addEventListener("focus",u);window.addEventListener("blur",
v);document.hasFocus()?p():e=!0},disable:function(){e=c=!1;clearTimeout(n);n=void 0;m=0;window.removeEventListener("focus",u);window.removeEventListener("blur",v)},setTimings:function(q){var E=uc(q);if(!E.isValid)return I(E.error),this;h=q;return this},isEnabled:function(){return c}}}function ud(){var a=[[/g/g,"10"],[/h/g,"11"],[/i/g,"12"],[/j/g,"13"],[/k/g,"14"],[/l/g,"15"],[/m/g,"16"],[/n/g,"17"],[/o/g,"18"],[/p/g,"19"],[/q/g,"1a"],[/r/g,"1b"],[/s/g,"1c"],[/t/g,"1d"],[/u/g,"1e"],[/v/g,"1f"],[/w/g,
"20"],[/x/g,"21"],[/y/g,"22"],[/z/g,"23"],[/_/g,"3e"],[/-/g,"3f"]],c=/^[0-9a-f]{16}$/;return function(e){if(e&&!c.test(e)){e=e.toLowerCase().substr(4,16);for(var g=0;g<a.length;g+=1)e=e.replace(a[g][0],a[g][1]);e=e.substr(0,16)}return e}}function vd(a){return{transformIfAMPCookie:ud(),getCookieName:function(c){return a.getCookiesConfig().cookieNamePrefix+c+"."+a.getCookiesConfig().trackerSiteId+"."+a.getCookiesConfig().domainHash},getCookie:function(c){return a.getCookiesConfig().cookiesDisabled?
0:(c=(new RegExp("(^|;)[ ]*"+c+"=([^;]*)")).exec(a.documentAlias.cookie))?a.decodeWrapper(c[2])||0:0},setCookie:function(c,e,g){var h=a.getCookiesConfig();h.msToExpire=g?g.msToExpire||h.msToExpire:h.msToExpire;h.path=g?g.path||h.path:h.path;if(!h.cookiesDisabled){g=a.documentAlias;e=a.encodeWrapper(e);if(h.msToExpire){var n=new Date;n.setTime(n.getTime()+h.msToExpire)}c=c+"="+e+(h.msToExpire?";expires="+n.toGMTString():"")+";path="+(h.path||"/")+(h.domain?";domain="+h.domain:"")+(h.isSecure?";secure":
"")+";SameSite=Lax";g.cookie=c}},deleteCookie:function(c){this.setCookie(c,"",{msToExpire:-86400})},hasCookies:function(){if(a.getCookiesConfig().cookiesDisabled)return"0";if(!w(a.navigatorAlias.cookieEnabled)){var c=this.getCookieName("_pk_testcookie");this.setCookie(c,"1");var e="1"===this.getCookie(c)?"1":"0";this.deleteCookie(c);return e}return a.navigatorAlias.cookieEnabled?"1":"0"}}}function wc(a){var c=function(Ba,Z){return Ba<<Z|Ba>>>32-Z},e=function(Ba){var Z="",aa;for(aa=7;0<=aa;aa--){var Cb=
Ba>>>4*aa&15;Z+=Cb.toString(16)}return Z},g,h=[],n=1732584193,m=4023233417,p=2562383102,u=271733878,v=3285377520,r=[];a=unescape(encodeURIComponent(a));var q=a.length;for(g=0;g<q-3;g+=4){var E=a.charCodeAt(g)<<24|a.charCodeAt(g+1)<<16|a.charCodeAt(g+2)<<8|a.charCodeAt(g+3);r.push(E)}switch(q&3){case 0:g=2147483648;break;case 1:g=a.charCodeAt(q-1)<<24|8388608;break;case 2:g=a.charCodeAt(q-2)<<24|a.charCodeAt(q-1)<<16|32768;break;case 3:g=a.charCodeAt(q-3)<<24|a.charCodeAt(q-2)<<16|a.charCodeAt(q-1)<<
8|128}for(r.push(g);14!==(r.length&15);)r.push(0);r.push(q>>>29);r.push(q<<3&4294967295);for(a=0;a<r.length;a+=16){for(g=0;16>g;g++)h[g]=r[a+g];for(g=16;79>=g;g++)h[g]=c(h[g-3]^h[g-8]^h[g-14]^h[g-16],1);E=n;q=m;var K=p;var J=u;var V=v;for(g=0;19>=g;g++){var H=c(E,5)+(q&K|~q&J)+V+h[g]+1518500249&4294967295;V=J;J=K;K=c(q,30);q=E;E=H}for(g=20;39>=g;g++)H=c(E,5)+(q^K^J)+V+h[g]+1859775393&4294967295,V=J,J=K,K=c(q,30),q=E,E=H;for(g=40;59>=g;g++)H=c(E,5)+(q&K|q&J|K&J)+V+h[g]+2400959708&4294967295,V=J,J=
K,K=c(q,30),q=E,E=H;for(g=60;79>=g;g++)H=c(E,5)+(q^K^J)+V+h[g]+3395469782&4294967295,V=J,J=K,K=c(q,30),q=E,E=H;n=n+E&4294967295;m=m+q&4294967295;p=p+K&4294967295;u=u+J&4294967295;v=v+V&4294967295}H=e(n)+e(m)+e(p)+e(u)+e(v);return H.toLowerCase()}function Ca(a,c){if("undefined"===typeof a)return!0;if("object"!==O(a)||null===a)return I("[".concat(c,"]: parameter 'options' have to be of type object or undefined. Received: ").concat(JSON.stringify(a))),!1;if("string"===typeof a.currencyCode||"undefined"===
typeof a.currencyCode)return!0;I("[".concat(c,"]: parameter 'options.currencyCode' has to be of type string or undefined Received: ").concat(JSON.stringify(a.currencyCode)));return!1}function W(a,c,e,g){if(a.addEventListener)return a.addEventListener(c,e,g),!0;if(a.attachEvent)return a.attachEvent("on"+c,e);a["on"+c]=e}function wd(a){var c={};if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&navigator.mimeTypes.length)for(var e in Db)if(Object.prototype.hasOwnProperty.call(Db,e)){var g=
navigator.mimeTypes[Db[e]];c[e]=g&&g.enabledPlugin?"1":"0"}ab(navigator.javaEnabled)&&navigator.javaEnabled()&&(c.java="1");ab(window.GearsFactory)&&(c.gears="1");c.cookie=a()}a=parseInt(screen.width,10);e=parseInt(screen.height,10);c.res=a+"x"+e;return c}function xc(a,c,e){if(c)return c;a=e.toAbsoluteUrl(a);c=String(a);-1!==c.indexOf("?")&&(c=a.indexOf("?"),a=a.slice(0,c));Aa(a,"ppms.php")?a=qc(a,8):Aa(a,".php")&&(c=a.lastIndexOf("/"),a=a.slice(0,c+1));Aa(a,"/js/")&&(a=qc(a,3));return a}function yc(a,
c){c||(c=wc);return c((navigator.userAgent||"")+(navigator.platform||"")+JSON.stringify(a)).slice(0,6)}function zc(a){var c=Math.floor((new Date).getTime()/1E3);a=yc(a);return String(c)+a}function xd(a,c,e,g){if(!e.crossDomainTrackingEnabled)return"";g||(g=yb);a=g(a,e.configVisitorIdUrlParameter);if(!a)return"";a=String(a);g=/^[a-zA-Z0-9]+$/;if(16===a.length&&g.test(a))return a;if(32===a.length&&g.test(a)){a:{g=a.substr(16,32);e=e.configVisitorIdUrlParameterTimeoutInSeconds;g=String(g);c=yc(c);var h=
c.length,n=g.substr(-1*h,h);if((g=parseInt(g.substr(0,g.length-h),10))&&n&&n===c){c=Math.floor((new Date).getTime()/1E3);if(0>=e){e=!0;break a}if(c>=g&&c<=g+e){e=!0;break a}}e=!1}if(e)return a.substr(0,16)}return""}function Ac(a,c,e,g){if(a&&c.hasNodeAttribute(a,"href")){var h=c.getAttributeValueFromNode(a,"href");h&&!Za(h,g.trackerUrl)&&(h=(g.crossDomainTrackingLinkDecorator||Bc)(h,e+zc(g.browserFeatures),g.configVisitorIdUrlParameter),null!==h&&c.setAnyAttribute(a,"href",h))}}function Bc(a,c,e){a=
mc(a,e);a=String(a);c||(c="");var g=document.createElement("a");g.href=a;a=g.search.split("&");a.push(encodeURIComponent(e)+"="+encodeURIComponent(c));""===a[0]&&a.shift();g.search=a.join("&");return g.href}function Eb(a,c,e,g){if(!c)return"";var h="",n;for(n in a)if(Object.prototype.hasOwnProperty.call(a,n)&&a[n]&&"function"===typeof a[n][c]){var m=(0,a[n][c])(e||{},g);m&&(h+=m)}return h}function bb(a,c,e){w(e)||(e="");try{return a[c]||e}catch(g){return e}}function yd(a){if(!a)return!0;var c,e=!0;
for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(e=!1);return e}function Pa(){var a,c;for(a=0;a<arguments.length;a+=1){var e=null;arguments[a]&&arguments[a].slice&&(e=arguments[a].slice());var g=arguments[a];var h=g.shift();if(P(h)&&0<h.indexOf("::")){var n=h.split("::");var m=n[0];h=n[1];"object"===O(sa[m])&&"function"===typeof sa[m][h]?sa[m][h].apply(sa[m],g):e&&cb.push(e)}else for(c=0;c<S.length;c++)if(P(h)){m=S[c];if(0<h.indexOf("."))if(n=h.split("."),m&&"object"===O(m[n[0]]))m=m[n[0]],
h=n[1];else if(e){cb.push(e);break}m[h]?m[h].apply(m,g):I("The method '"+h+'\' was not found in "_paq" variable.  Please have a look at the Piwik tracker documentation');if("addTracker"===h)break;if("setTrackerUrl"===h||"setSiteId"===h)break}else h.apply(S[c],g)}}function db(a,c,e,g){if(a.removeEventListener)return a.removeEventListener(c,e,g),!0;if(a.detachEvent)return a.detachEvent("on"+c,e);a["on"+c]===e&&delete a["on"+c]}function Da(a){"complete"===B.readyState?a():z.addEventListener?z.addEventListener("load",
a):z.attachEvent&&z.attachEvent("onload",a)}function Qa(a){var c=!1;(c=B.attachEvent?"complete"===B.readyState:"loading"!==B.readyState)?a():(B.addEventListener?W(B,"DOMContentLoaded",function g(){B.removeEventListener("DOMContentLoaded",g,!1);c||(c=!0,a())}):B.attachEvent&&(B.attachEvent("onreadystatechange",function g(){"complete"===B.readyState&&(B.detachEvent("onreadystatechange",g),c||(c=!0,a()))}),B.documentElement.doScroll&&z===z.top&&function h(){if(!c){try{B.documentElement.doScroll("left")}catch(n){setTimeout(h,
0);return}c=!0;a()}}()),W(z,"load",function(){c||(c=!0,a())},!1))}function zd(a,c){var e=B.createElement("script");e.type="text/javascript";e.src=a;e.readyState?e.onreadystatechange=function(){var g=this.readyState;if("loaded"===g||"complete"===g)e.onreadystatechange=null,c()}:e.onload=c;B.getElementsByTagName("head")[0].appendChild(e)}function Ad(){var a="";try{a=z.top.document.referrer}catch(c){if(z.parent)try{a=z.parent.document.referrer}catch(e){a=""}}""===a&&(a=B.referrer);return a}function ba(a){return a&&
String(a)===a?a.replace(/^\s+|\s+$/g,""):a}function Cc(a,c){return a&&c?a.contains?a.contains(c):a===c?!0:a.compareDocumentPosition?!!(a.compareDocumentPosition(c)&16):!1:!1}function Fb(a){function c(g,h){if(z.getComputedStyle)return B.defaultView.getComputedStyle(g,null)[h];if(g.currentStyle)return g.currentStyle[h]}function e(g,h,n,m,p,u,v){var r=g.parentNode,q;a:{for(q=g.parentNode;q;){if(q===B){q=!0;break a}q=q.parentNode}q=!1}if(!q)return!1;if(9===r.nodeType)return!0;if("0"===c(g,"opacity")||
"none"===c(g,"display")||"hidden"===c(g,"visibility"))return!1;w(h)&&w(n)&&w(m)&&w(p)&&w(u)&&w(v)||(h=g.offsetTop,p=g.offsetLeft,m=h+g.offsetHeight,n=p+g.offsetWidth,u=g.offsetWidth,v=g.offsetHeight);if(a===g&&(0===v||0===u)&&"hidden"===c(g,"overflow"))return!1;if(r){if("hidden"===c(r,"overflow")||"scroll"===c(r,"overflow"))if(p+1>r.offsetWidth+r.scrollLeft||p+u-1<r.scrollLeft||h+1>r.offsetHeight+r.scrollTop||h+v-1<r.scrollTop)return!1;g.offsetParent===r&&(p+=r.offsetLeft,h+=r.offsetTop);return e(r,
h,n,m,p,u,v)}return!0}return a?e(a):!1}function ta(){var a=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)(&segment=.*)?$/.exec(B.referrer);if(a){var c=a[2],e=a[3];(a=a[4])?0===a.indexOf("&segment=")&&(a=a.substr(9)):a="";z.name="Piwik_Overlay###"+c+"###"+e+"###"+a}c=z.name.split("###");return 4===c.length&&"Piwik_Overlay"===c[0]}function Bd(a,c,e){var g=z.name.split("###"),h=g[1],n=g[2],m=g[3],p=xc(a,c,C);zd(p+"plugins/Overlay/client/client.js?v=1",
function(){Piwik_Overlay_Client.initialize(p,e,h,n,m)})}function Gb(a,c){function e(b){if(!1===Hb||!0===Ib){var d=new Date;null!==Jb&&18E5<d-Jb||(d=H("ping=".concat(b),null,"ping"),b=b!==ra.PeriodicHeartbeat,p(d,L,null,b,b?"beacon":null))}}function g(b,d){var f=new Image(1,1);f.onload=function(){Ea=0;"function"===typeof d&&d()};b=-1!==b.indexOf("send_image=0")?b.replace("&send_image=0","&send_image=1"):b+"&send_image=1";f.src=Y+(0>Y.indexOf("?")?"?":"&")+b}function h(b,d,f){w(f)&&null!==f||(f=!0);
try{var k=z.XMLHttpRequest?new z.XMLHttpRequest:z.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;k.open("POST",Y,!0);k.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!f?4===this.readyState&&"function"===typeof d&&d():g(b,d)};k.setRequestHeader("Content-Type",Kb);k.send(b)}catch(l){f&&g(b,d)}}function n(b){b=(new Date).getTime()+b;if(!eb||b>eb)eb=b}function m(b,d){var f=(new Date).getTime();Dc=f;Fa&&f<Fa?(f=Fa-f,setTimeout(b,f),d&&n(f+50),Fa+=50):(!1===
Fa&&(Fa=f+800),b())}function p(b,d,f,k,l){if(Lb){var A=Ec.getState();if("loading"===A.state){fb.push({type:"single",request:b,delay:d,callback:f,force:k,method:l});return}"available"===A.state&&(b+=Fc(A.hints))}ab(Ra)&&(b=Ra(b));if(!gb&&b){var y=l||hb,N=!f&&ua.sendBeacon&&z.Blob&&65536>=b.length,D=!0;l=function(){if("beacon"===y&&N){var fa=new z.Blob([String(b)],{type:Kb});ua.sendBeacon(Y,fa)?D=!1:h(b,f)}else"POST"===y||2E3<String(b).length?h(b,f):g(b,f);D&&n(d)};k?l():m(l,D)}}function u(b,d){var f=
gb?!1:b&&b.length;if(f){if(Lb){f=Ec.getState();if("loading"===f.state){fb.push({type:"bulk",requests:b,delay:d});return}if("available"===f.state)for(var k=0;k<b.length;k++)b[k]+=Fc(f.hints)}if(ab(Ra)){f=[];for(k=0;k<b.length;k++){var l=Ra(b[k]);l&&f.push(l)}if(0>=f.length)return;b=f}var A='{"requests":["?'+b.join('","?')+'"]}';m(function(){h(A,null,!1);"beacon"!==hb&&n(d)},!1)}}function v(){Gc=Hc((ib||Sa)+(jb||"/")).slice(0,4)}function r(){var b=M.getCookieName("cvar");b=M.getCookie(b);return b.length&&
(b=JSON.parse(b),qa(b))?b:{}}function q(){Ga||(Ga=xd(kb,ha,{crossDomainTrackingEnabled:Ha,configVisitorIdUrlParameter:"pk_vid",configVisitorIdUrlParameterTimeoutInSeconds:Ic},Jc));var b=Math.round((new Date).getTime()/1E3),d=M.getCookieName("id");return(d=M.getCookie(d))?(d=d.split("."),d[0]=M.transformIfAMPCookie(d[0]),6>d.length&&(d[1]=b,d[2]=0,d[3]=b,d[4]="",d[5]=""),d.unshift("0"),Ga.length&&(d[1]=Ga),d):d=["1",Ga.length?Ga:"0"===M.hasCookies()?"":Hc((ua.userAgent||"")+(ua.platform||"")+JSON.stringify(ha)+
(new Date).getTime()+Math.random()).slice(0,16),b,0,b,"",""]}function E(){var b=q(),d=b[0],f=b[1],k=b[2],l=b[3],A=b[4],y=b[5];w(b[6])||(b[6]="");return{newVisitor:d,uuid:f,createTs:k,visitCount:l,currentVisitTs:A,lastVisitTs:y,lastEcommerceOrderTs:b[6]}}function K(b){if(va){var d=Math.round((new Date).getTime()/1E3);w(b)||(b=E());b=b.uuid+"."+b.createTs+"."+b.visitCount+"."+d+"."+b.lastVisitTs+"."+b.lastEcommerceOrderTs;M.setCookie(M.getCookieName("id"),b,{msToExpire:Mb})}}function J(){var b=wa;wa=
!1;var d;for(d=0;d<Nb.length;d++){var f=M.getCookieName(Nb[d]);0!==M.getCookie(f)&&M.deleteCookie(f)}wa=b}function V(b){if(b&&qa(b)){var d=[];for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&d.push(f);var f={};d.sort();var k=d.length,l;for(l=0;l<k;l++)f[d[l]]=b[d[l]];return f}}function H(b,d,f,k){function l(ia,Cd){var Kc=JSON.stringify(ia);return 2<Kc.length?"&"+Cd+"="+G(Kc):""}var A=new Date;var y=Math.round(A.getTime()/1E3);var N=T,D=M.getCookieName("ses"),fa=M.getCookieName("cvar"),xa=M.getCookie(D),
Ob=Ta||kb;wa&&J();if(gb)return"";D=E();w(k)||(k="");var F=B.characterSet||B.charset;F&&"utf-8"!==F.toLowerCase()||(F=null);!xa&&(xa=Ia/1E3,!D.lastVisitTs||y-D.lastVisitTs>xa)&&(D.visitCount++,D.lastVisitTs=D.currentVisitTs);Ab(b,"action_name=")&&(Hb=lb,Ib=!!D.uuid,Jb=new Date);b+="&idsite="+va+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+A.getHours()+"&m="+A.getMinutes()+"&s="+A.getSeconds()+"&url="+G($a(Ob,{discardHashTag:Ua,visitorIdUrlParameter:"pk_vid"}))+(Pb.length?"&urlref="+G($a(Pb,{discardHashTag:Ua,
visitorIdUrlParameter:"pk_vid"})):"")+(Ja&&Ja.length?"&uid="+G(Ja):"")+(lb?"&uia=1":"")+(D.uuid?"&_id="+D.uuid:"")+"&_idts="+D.createTs+"&_idvc="+D.visitCount+(D.lastVisitTs?"&_viewts="+D.lastVisitTs:"")+(String(D.lastEcommerceOrderTs).length?"&_ects="+D.lastEcommerceOrderTs:"")+(F?"&cs="+G(F):"")+"&ts_n="+G(mb||Qb)+"&ts_v="+G(Rb||Sb)+(Lc?"":"&rmip=1")+(Mc&&lb?"&dda=1":"");if(!Nc)for(x in ha)Object.prototype.hasOwnProperty.call(ha,x)&&(b+="&"+x+"="+ha[x]);A=[];if(d)for(x in d)Object.prototype.hasOwnProperty.call(d,
x)&&/^dimension\d+$/.test(x)&&(y=x.replace("dimension",""),A.push(parseInt(y,10)),A.push(String(y)),b+="&"+x+"="+d[x],delete d[x]);d&&yd(d)&&(d=null);for(x in ca)Object.prototype.hasOwnProperty.call(ca,x)&&(y=-1===ea(A,x))&&(y=RegExp("[^\x00-\u007f]"),b=(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&null!==ca[x].match(y)?b+("&dimension"+x+"="+encodeURIComponent(ca[x])):b+("&dimension"+x+"="+ca[x]));for(x in ma)Object.prototype.hasOwnProperty.call(ma,x)&&(y=
-1===ea(A,x))&&(b+="&dimension"+encodeURIComponent(x)+"="+encodeURIComponent(ma[x]));d?b+="&data="+G(JSON.stringify(d)):na&&(b+="&data="+G(JSON.stringify(na)));d=V(oa);A=V(nb);b+=l(d,"cvar");b+=l(A,"e_cvar");if(T){b+=l(T,"_cvar");for(x in N)Object.prototype.hasOwnProperty.call(N,x)&&(""===T[x][0]||""===T[x][1])&&delete T[x];Oc&&M.setCookie(fa,JSON.stringify(T),{msToExpire:Ia})}var x=qd();N=null;Tb&&(Ub?N=Ub:x&&x.requestStart&&x.responseEnd&&(N=x.responseEnd-x.requestStart),null!==N&&(b+="&gt_ms="+
Math.max(N,0)));N=x&&x.loadEventEnd&&0!==x.loadEventEnd&&x.fetchStart&&0!==x.fetchStart;Tb&&("log"===f||"ping"===f)&&2>=ob&&!Pc&&N&&(b+=rd(x),Pc=!0);pb&&(b+="&pv_id="+pb);D.lastEcommerceOrderTs=w(k)&&String(k).length?k:D.lastEcommerceOrderTs;K(D);M.setCookie(M.getCookieName("ses"),"*",{msToExpire:Ia});b+=Eb(Va,f,{tracker:Dd,request:b});Vb.length&&(b+="&"+Vb);return b}function Ba(b){if(!qa(b))return I("Invalid ecommerce product: "+JSON.stringify(b)),!1;if(!Object.prototype.hasOwnProperty.call(b,"sku"))return I("Missing required SKU property in ecommerce product: "+
JSON.stringify(b)+"."),!1;var d=O(b.sku);return"string"!==d&&"number"!==d?(I("Product.sku has to be of type string or number. Received: ".concat(d,". In product: ").concat(JSON.stringify(b))),!1):Object.prototype.hasOwnProperty.call(b,"customDimensions")&&!qa(b.customDimensions)?(I('Invalid "customDimensions" property. Expected Object type, but got: '+JSON.stringify(b)+"."),!1):!0}function Z(b,d,f,k){var l=new Date,A=[];var y=""+ja("");y+="&e_t="+b;null!==k&&void 0!==k&&k.currencyCode&&(y+="&cur="+
k.currencyCode);if(f){b=f.orderId;k=f.grandTotal;var N=f.subTotal;var D=f.tax;var fa=f.shipping;f=f.discount;if(b){y+="&ec_id="+G(b);var xa=Math.round(l.getTime()/1E3)}y+="&revenue="+k;za(N)&&(y+="&ec_st="+N);za(D)&&(y+="&ec_tx="+D);za(fa)&&(y+="&ec_sh="+fa);za(f)&&(y+="&ec_dt="+f)}if(d){for(l=0;l<d.length;l+=1){w(d[l].name)||(d[l].name="");if(!w(d[l].category))d[l].category="";else if(d[l].category instanceof Array)for(f=0;f<d[l].category.length;f+=1)P(d[l].category[f])||(d[l].category[f]="");w(d[l].price)&&
0!==String(d[l].price).length||(d[l].price=0);w(d[l].quantity)&&0!==String(d[l].quantity).length||(d[l].quantity=1);w(d[l].brand)&&0!==String(d[l].brand).length||(d[l].brand="");w(d[l].variant)&&0!==String(d[l].variant).length||(d[l].variant="");w(d[l].customDimensions)||(d[l].customDimensions={});f=A;b=f.push;a:for(k=[String(d[l].sku),String(d[l].name),d[l].category,d[l].price,d[l].quantity,d[l].brand,String(d[l].variant),d[l].customDimensions].slice();0<k.length;){N=k[k.length-1];if(!(D=""===N)&&
(D=qa(N)))b:{D=void 0;for(D in N)if(Object.hasOwnProperty.call(N,D)){D=!1;break b}D=!0}if(D)k.pop();else break a}b.call(f,k)}y+="&ec_products="+G(JSON.stringify(A))}y=H(y,na,"ecommerce",xa);p(y,L)}function aa(b){var d,f=!0;if(b instanceof Array){for(d=0;d<b.length;d+=1)f=f&&Ba(b[d]);return f}I("Invalid ecommerce products. Expected value: array of objects. Recieved: "+JSON.stringify(b)+".")}function Cb(b,d){var f;if("object"!==O(b)||null===b)return I("Invalid paymentInformation. Expected object. Recieved: "+
JSON.stringify(b)+"."),!1;for(f=0;f<d.length;f+=1){var k=d[f];var l=b[k];if("orderId"===k){if(!w(l)||""===String(l))return I('Invalid paymentInformation. Expected object containing "'+k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}else if(!za(l))return I('Invalid paymentInformation. Expected object containing [number] "'+k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}return!0}function Qc(b,d,f){Ca(f,"ecommerceCartUpdate")||(f=void 0);za(d)?aa(b)&&Z("cart-update",b,{grandTotal:d},f):
I('ecommerceCartUpdate requires [number] "grandTotal" parameter. Recieved: '+JSON.stringify(d)+".")}function Rc(b,d,f){Ca(f,"ecommerceOrder")||(f=void 0);aa(b)&&Cb(d,["orderId","grandTotal"])&&Z("order",b,d,f)}function Sc(){var b,d=[];if(X){for(b in X)if(Object.prototype.hasOwnProperty.call(X,b)){var f={sku:X[b][0],name:X[b][1],category:X[b][2],price:X[b][3],quantity:X[b][4]};d.push(f)}return d}return[]}function ja(b){b=(b=b||qb)&&b.text?b.text:b;if(!P(b)){var d=document.getElementsByTagName("title");
d&&w(d[0])&&(b=d[0].text)}return"action_name="+G(b)}function rb(b,d,f,k){if(b=C.buildInteractionRequestParams(b,d,f,k))return H("".concat(b,"&").concat(ja()),null,"contentInteraction")}function Wb(b,d){if(!b||!d)return!1;var f,k=C.findTargetNodes(b);for(f=0;f<k.length;f++){var l=k[f];if(Cc(l,d)&&C.shouldIgnoreInteraction(l))return!1}k=C.findTargetNodesNoDefault(b);if(!k||0===k.length)return!0;for(f=0;f<k.length;f++)if(l=k[f],Cc(l,d))return!0;return!1}function Tc(b,d,f){if(b){var k=C.findParentContentNode(b);
if(k&&Wb(k,b)&&(b=C.buildContentBlock(k)))return!b.target&&f&&(b.target=f),C.buildInteractionRequestParams(d,b.name,b.piece,b.target)}}function Uc(b){if(!pa||!pa.length)return!1;var d,f;for(d=0;d<pa.length;d++)if((f=pa[d])&&f.name===b.name&&f.piece===b.piece&&f.target===b.target)return!0;return!1}function Vc(b){return function(d){if(b){var f=C.findParentContentNode(b),k;d&&(k=d.target||d.srcElement);k||(k=b);if(Wb(f,k)){"beacon"!==hb&&n(L);t.isLinkElement(b)&&t.hasNodeAttributeWithValue(b,"href")&&
t.hasNodeAttributeWithValue(b,C.CONTENT_TARGET_ATTR)&&(d=t.getAttributeValueFromNode(b,"href"),!Za(d,Y)&&b.wasContentTargetAttrReplaced&&t.setAnyAttribute(b,C.CONTENT_TARGET_ATTR,""));d=tc(b,C,{configTrackerUrl:Y,configDownloadClasses:Xb,configLinkClasses:Yb,configDownloadExtensions:ka,configHostsAlias:la});if(Ka&&d&&d.type)return d.type;if(k=C.buildContentBlock(f))if(f=k.name,d=k.piece,k=t.getAttributeValueFromNode(b,C.CONTENT_TARGET_ATTR)||k.target,f=rb("click",f,d,k))return p("".concat(f,"&").concat(ja()),
L),f}}}}function Wc(b){if(b&&b.length){var d,f,k;for(d=0;d<b.length;d++){var l=C.findTargetNodes(b[d]);for(k=0;k<l.length;k++)(f=l[k])&&!f.contentInteractionTrackingSetupDone&&(f.contentInteractionTrackingSetupDone=!0,W(f,"click",Vc(f)))}}}function Xc(b,d){if(!b||!b.length)return[];var f,k;for(f=0;f<b.length;f++)Uc(b[f])?(b.splice(f,1),f--):pa.push(b[f]);if(!b||!b.length)return[];Wc(d);var l=[];for(f=0;f<b.length;f++)(k=H("".concat(C.buildImpressionRequestParams(b[f].name,b[f].piece,b[f].target),
"&").concat(ja()),void 0,"contentImpressions"))&&l.push(k);return l}function Wa(b){var d=C.collectContent(b);return Xc(d,b)}function Zb(b){if(!b||!b.length)return[];var d;for(d=0;d<b.length;d++)C.isNodeVisible(b[d])||(b.splice(d,1),d--);return b&&b.length?Wa(b):[]}function Yc(b,d,f){b=C.buildImpressionRequestParams(b,d,f);return H("".concat(b,"&").concat(ja()),null,"contentImpression")}function Zc(b,d){if(b){var f=C.findParentContentNode(b);if(f=C.buildContentBlock(f))return d||(d="Unknown"),rb(d,
f.name,f.piece,f.target)}}function $c(b,d,f,k,l,A){if(0===ba(String(b)).length||0===ba(String(d)).length)return I("Error while logging event: Parameters `category` and `action` must not be empty or filled with whitespaces"),!1;var y=H;b="e_c="+G(b)+"&e_a="+G(d)+(w(f)?"&e_n="+G(f):"")+(w(k)?"&e_v="+G(k):"");l=y(b+"&"+ja(""),l,"event");p(l,L,A)}function ad(b,d,f,k,l){d="".concat(ja(),"&").concat(d,"=").concat(G($a(b,{discardHashTag:Ua,visitorIdUrlParameter:"pk_vid"})));(b=Tc(l,"click",b))&&(d+="&"+
b);f=H(d,f,"link");p(f,L,k,!0,"beacon")}function U(b){var d,f,k=["","webkit","ms","moz"];if(!bd)for(f=0;f<k.length;f++){var l=k[f];if(Object.prototype.hasOwnProperty.call(B,pc(l,"hidden"))){"prerender"===B[pc(l,"visibilityState")]&&(d=!0);break}}d?W(B,l+"visibilitychange",function y(){B.removeEventListener(l+"visibilitychange",y,!1);b()}):b()}function $b(b){if(Ha){var d=zb(b);if(od(d,la)){Ac(d,t,E().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:Y,browserFeatures:ha,crossDomainTrackingLinkDecorator:ac});
return}}if((d=tc(b,C,{configTrackerUrl:Y,configDownloadClasses:Xb,configLinkClasses:Yb,configDownloadExtensions:ka,configHostsAlias:la}))&&d.type)ad(d.href,d.type,void 0,null,b);else if(Ha){b=zb(b);d=C;var f=la,k=Sa,l=t.getAttributeValueFromNode(b,"href");if(l)if(l=String(l),0!==l.indexOf("//")&&0!==l.indexOf("http://")&&0!==l.indexOf("https://"))d=!1;else{var A=lc(l),y=A.pathname||Ya(l,d);l=(A.hostname||Na(l)).toLowerCase();d=sc(l,y,f,d)&&!xb(k,Oa(l))?!0:!1}else d=!1;d&&Ac(b,t,E().uuid,{configVisitorIdUrlParameter:"pk_vid",
configTrackerUrl:Y,browserFeatures:ha,crossDomainTrackingLinkDecorator:ac})}}function Xa(b){return function(d){d=d||z.event;a:{var f=d;var k=f.which,l=O(f.button);k||"undefined"===l||(B.all&&!B.addEventListener?f.button&1?k=1:f.button&2?k=3:f.button&4&&(k=2):0===f.button||"0"===f.button?k=1:f.button&1?k=2:f.button&2&&(k=3));switch(k){case 1:f="left";break a;case 2:f="middle";break a;case 3:f="right";break a}f=void 0}k=d.target||d.srcElement;"click"===d.type?(d=!1,b&&"middle"===f&&(d=!0),k&&!d&&$b(k)):
"mousedown"===d.type?"middle"===f&&k?(sb=f,tb=k):sb=tb=null:"mouseup"===d.type?(f===sb&&k===tb&&$b(k),sb=tb=null):"contextmenu"===d.type&&$b(k)}}function Ed(b){function d(k){var l=k.target;if(l.closest)l=l.closest("a");else for(;l&&"A"!==l.tagName;)l=l.parentNode;bc&&l&&!Bb(cd,"ignore").test(l.className)&&Xa(b)(k)}function f(){db(document.body,"click",d,!1);b&&(db(document.body,"mouseup",d,!1),db(document.body,"mousedown",d,!1),db(document.body,"contextmenu",d,!1))}Ka||(W(document.body,"click",d,
!1),b&&(W(document.body,"mouseup",d,!1),W(document.body,"mousedown",d,!1),W(document.body,"contextmenu",d,!1)),Ka=f)}function dd(b,d,f){function k(){l=!0}if(La)return!0;La=!0;var l=!1,A,y;Da(function(){function N(F){setTimeout(function(){La&&(l=!1,f.trackVisibleContentImpressions(),N(F))},F)}function D(F){setTimeout(function(){La&&(l&&(l=!1,f.trackVisibleContentImpressions()),D(F))},F)}function fa(F){if(!F)return!1;var x=F.getBoundingClientRect();if(0>=x.width||0>=x.height)return!1;x=null;z.getComputedStyle?
x=B.defaultView.getComputedStyle(F,null):!x&&F.currentStyle?x=F.currentStyle:x||(x={});return"0"===x.opacity||"none"===x.display||"hidden"===x.visibility?!1:F.parentNode instanceof Element?fa(F.parentNode):!0}function xa(F){var x=[],ia;for(ia=0;ia<F.length;ia+=1)F[ia].isIntersecting&&fa(F[ia].target)&&C.isOrWasNodeInViewport(F[ia].target)&&x.push(F[ia].target);F=Wa(x);u(F,L)}function Ob(){if(z.IntersectionObserver){ya||(ya=new z.IntersectionObserver(xa,{threshold:0}));var F=C.findContentNodes();for(y=
0;y<F.length;y+=1)F[y].getAttribute(C.CONTENT_WATCHED_ATTR)||(ya.observe(F[y]),F[y].setAttribute(C.CONTENT_WATCHED_ATTR,"1"));return!0}return!1}(b||d&&0<d)&&Ob();if(b){A=["scroll","resize"];for(y=0;y<A.length;y++)B.addEventListener?B.addEventListener(A[y],k):z.attachEvent("on"+A[y],k);D(100)}d&&0<d&&(d=parseInt(d,10),N(d))})}function ed(b,d,f,k){if(cc){var l=String(b).substring(0,16E3);U(function(){var A=d+":"+f;k&&(A+=":"+k);var y=JSON.stringify({category:"JavaScript Errors",action:A,message:l});
fd&&-1!==ea(dc,y)||(dc.push(y),$c("JavaScript Errors",A,l))})}}var ub={},Dd=this,ec=nd(B.domain,z.location.href,Ad()),Sa=Oa(ec[0]),kb=ec[1],Pb=ec[2],cc=!1,hb="beacon",Lc=!0,Mc=!1,Lb=!1,Kb="application/x-www-form-urlencoded; charset=UTF-8",Y=a||"",fc="",Vb="",va=c||"",lb=!1,Nc=!1,Hb=null,Ib=null,Ja="",Ga="",gc=10,Ta,qb="",ka="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),
la=[Sa],cd=[],Xb=[],Yb=[],L=500,Jb=null,gd=!1,Ua,na,hd="_pk_",Ic=180,ib,jb,id=!1,wa=!1,jd=!0,gb,bd,Mb=339552E5,Ia=18E5,Tb=!0,Ub=0,Oc=!1,T=!1,Ra,oa={},nb={},ca={},ma={},hc=200,X={},ha={},pa=[],La=!1,ya,Fa=!1,Ka=!1,bc=!1,Ha=!1,ac=Bc,Jc=yb,Dc=null,sb,tb,Hc=wc,Gc,pb,ob=0,fd=!1,dc=[],Nb=["id","ses","cvar"],Qb="jstc",Sb="2.26.0",mb="",Rb="",Ec=sd({onResolve:function(){for(var b=0;b<fb.length;b++){var d=fb[b];if("single"===d.type)p(d.request,d.delay,d.callback,d.force,d.method);else if("bulk"===d.type)u(d.requests,
d.delay);else throw Error("[processQueue] unprocessable request type: ".concat(d));}}});try{qb=B.title}catch(b){qb=""}var Ma=td({onPing:e}),M=vd({decodeWrapper:Fd,encodeWrapper:G,getCookiesConfig:function(){return{cookiesDisabled:wa,domain:ib,path:jb,isSecure:id,trackerSiteId:va,cookieNamePrefix:hd,domainHash:Gc}},documentAlias:B,navigatorAlias:ua}),fb=[];this.setCustomVariableMaximumLength=function(b){hc=b};ha=wd(M.hasCookies);v();Eb(Va,"run",null,function(b,d){var f=null;if(P(b)&&!w(ub[b])&&d){if(qa(d))f=
d;else if(P(d))try{eval("hookObj ="+d)}catch(k){}ub[b]=f}return f});this.hook=ub;this.getHook=function(b){return ub[b]};this.getQuery=function(){return t};this.getContent=function(){return C};this.buildContentImpressionRequest=Yc;this.buildContentInteractionRequest=rb;this.buildContentInteractionRequestNode=Zc;this.getContentImpressionsRequestsFromNodes=Wa;this.getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet=Zb;this.trackCallbackOnLoad=Da;this.trackCallbackOnReady=Qa;this.buildContentImpressionsRequests=
Xc;this.wasContentImpressionAlreadyTracked=Uc;this.appendContentInteractionToRequestIfPossible=Tc;this.setupInteractionsTracking=Wc;this.trackContentImpressionClickInteraction=Vc;this.internalIsNodeVisible=Fb;this.isNodeAuthorizedToTriggerInteraction=Wb;this.getDomains=function(){return la};this.getConfigIdPageView=function(){return pb};this.getConfigDownloadExtensions=function(){return ka};this.enableTrackOnlyVisibleContent=function(b,d){return dd(b,d,this)};this.clearTrackedContentImpressions=function(){pa=
[]};this.getTrackedContentImpressions=function(){return pa};this.clearEnableTrackOnlyVisibleContent=function(){La=!1;ya&&ya.disconnect();ya=null};this.disableLinkTracking=function(){"function"===typeof Ka&&Ka();bc=Ka=!1};this.getConfigVisitorCookieTimeout=function(){return Mb};this.removeAllAsyncTrackersButFirst=function(){S=[S[0]]};this.ping=function(){var b=H("ping=6",null,"ping");p(b,L)};this.getVisitorId=function(){return E().uuid};this.getVisitorInfo=function(){return q()};this.setTrackerUrl=
function(b){Y=b};this.getTrackerUrl=function(){return Y};this.getPiwikUrl=function(){return xc(this.getTrackerUrl(),fc,C)};this.addTracker=function(b,d){if(!d)throw Error("A siteId must be given to add a new tracker");w(b)&&null!==b||(b=this.getTrackerUrl());var f=new Gb(b,d);S.push(f);return f};this.getSiteId=function(){return va};this.setSiteId=function(b){va=b;K();if(jd){var d=this.getTrackerUrl(),f=B.createElement("script");f.setAttribute("id","ppas_container_configuration");f.setAttribute("data-appid",
b);b=f.setAttribute;var k=B.createElement("a");k.href=d;b.call(f,"data-host",k.host);B.getElementsByTagName("head")[0].appendChild(f)}};this.setVisitorIdCookie=function(){K()};this.resetUserId=function(){Ja=""};this.setUserIsAnonymous=function(b){lb=b};this.setSessionIdStrictPrivacyMode=function(b){Nc=b};this.setTimingDataSamplingOnPageLoad=function(b){!0===b&&(b=1);!1===b&&(b=0);b=parseInt(b,10);0>b?b=0:100<b&&(b=100);gc=b};this.getTimingDataSamplingOnPageLoad=function(){return gc};this.setUserId=
function(b){w(b)&&b.length&&(Ja=b)};this.getUserId=function(){return Ja};this.setCustomData=function(b,d){qa(b)?na=b:(na||(na={}),na[b]=d)};this.getCustomData=function(){return na};this.setCustomRequestProcessing=function(b){Ra=b};this.appendToTrackingUrl=function(b){Vb=b};this.getRequest=function(b){return H(b)};this.addPlugin=function(b,d){Va[b]=d};this.setCustomDimension=function(b,d){b=parseInt(b,10);0<b&&(Object.prototype.hasOwnProperty.call(ma,b)?console.warn("Custom dimension "+b+' was already set by "setCustomDimensionValue" method. Value set by "setCustomDimension" will be ignored.'):
(w(d)||(d=""),P(d)||(d=String(d)),ca[b]=d))};this.getCustomDimension=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(ca,b))return ca[b]};this.deleteCustomDimension=function(b){b=parseInt(b,10);0<b&&(delete ca[b],delete ma[b])};this.setCustomDimensionValue=function(b,d){b=parseInt(b,10);0<b&&(w(d)||(d=""),P(d)||(d=String(d)),ma[b]=d,delete ca[b])};this.getCustomDimensionValue=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(ma,b))return ma[b]};this.setCustomVariable=
function(b,d,f,k){w(k)||(k="visit");w(d)&&(w(f)||(f=""),0<b&&(d=P(d)?d:String(d),f=P(f)?f:String(f),d=[d.slice(0,hc),f.slice(0,hc)],"visit"===k||2===k?(!1===T&&(T=r()),T[b]=d):"page"===k||3===k?oa[b]=d:"event"===k&&(nb[b]=d)))};this.getCustomVariable=function(b,d){w(d)||(d="visit");if("page"===d||3===d)var f=oa[b];else if("event"===d)f=nb[b];else if("visit"===d||2===d)!1===T&&(T=r()),f=T[b];return!w(f)||f&&""===f[0]?!1:f};this.deleteCustomVariable=function(b,d){this.getCustomVariable(b,d)&&this.setCustomVariable(b,
"","",d)};this.deleteCustomVariables=function(b){if("page"===b||3===b)oa={};else if("event"===b)nb={};else if("visit"===b||2===b)T={}};this.storeCustomVariablesInCookie=function(){Oc=!0};this.setLinkTrackingTimer=function(b){L=b};this.getLinkTrackingTimer=function(){return L};this.setDownloadExtensions=function(b){P(b)&&(b=b.split("|"));ka=b};this.addDownloadExtensions=function(b){var d;P(b)&&(b=b.split("|"));for(d=0;d<b.length;d++)ka.push(b[d])};this.removeDownloadExtensions=function(b){var d,f=
[];P(b)&&(b=b.split("|"));for(d=0;d<ka.length;d++)-1===ea(b,ka[d])&&f.push(ka[d]);ka=f};this.setDomains=function(b){la=P(b)?[b]:b;b=!1;for(var d=0;d<la.length;d++){var f=String(la[d]);if(xb(Sa,Oa(f))){b=!0;break}if((f=Ya(f,C))&&"/"!==f&&"/*"!==f){b=!0;break}}b||la.push(Sa)};this.enableCrossDomainLinking=function(){Ha=!0};this.disableCrossDomainLinking=function(){Ha=!1};this.isCrossDomainLinkingEnabled=function(){return Ha};this.customCrossDomainLinkDecorator=function(b){ac=b};this.customCrossDomainLinkVisitorIdGetter=
function(b){Jc=b};this.setCrossDomainLinkingTimeout=function(b){Ic=b};this.getCrossDomainLinkingUrlParameter=function(){var b=E().uuid;return G("pk_vid")+"="+G(b+zc(ha))};this.setIgnoreClasses=function(b){cd=P(b)?[b]:b};this.setRequestMethod=function(b){hb=b||"beacon"};this.setRequestContentType=function(b){Kb=b||"application/x-www-form-urlencoded; charset=UTF-8"};this.setReferrerUrl=function(b){Pb=b};this.setCustomUrl=function(b){var d=kb,f=Ua;nc(b)?Ta=b:"/"===b.slice(0,1)?Ta=nc(d)+"://"+Na(d)+b:
(d=$a(d,{discardHashTag:f,visitorIdUrlParameter:"pk_vid"}),f=d.indexOf("?"),0<=f&&(d=d.slice(0,f)),f=d.lastIndexOf("/"),f!==d.length-1&&(d=d.slice(0,f+1)),Ta=d+b)};this.getCurrentUrl=function(){return Ta||kb};this.setDocumentTitle=function(b){qb=b};this.setAPIUrl=function(b){fc=b};this.setDownloadClasses=function(b){Xb=P(b)?[b]:b};this.setLinkClasses=function(b){Yb=P(b)?[b]:b};this.discardHashTag=function(b){Ua=b};this.setCookieNamePrefix=function(b){hd=b;T=r()};this.setCookieDomain=function(b){ib=
Oa(b);v()};this.getCookieDomain=function(){return ib};this.hasCookies=function(){return"1"===M.hasCookies()};this.setSessionCookie=function(b,d,f){if(!b)throw Error("Missing cookie name");w(f)||(f=Ia);Nb.push(b);M.setCookie(M.getCookieName(b),d,{msToExpire:f})};this.getCookie=function(b){b=M.getCookie(M.getCookieName(b));return 0===b?null:b};this.setCookiePath=function(b){jb=b;v()};this.getCookiePath=function(){return jb};this.setVisitorCookieTimeout=function(b){Mb=1E3*b};this.setSessionCookieTimeout=
function(b){Ia=1E3*b};this.getSessionCookieTimeout=function(){return Ia};this.setReferralCookieTimeout=function(b){};this.setSecureCookie=function(b){id=b};this.disableCookies=function(){wa=!0;va&&J()};this.enableCookies=function(){wa=!1};this.deleteCookies=function(){J()};this.setSiteInspectorSetup=function(b){jd=b};this.setDoNotTrack=function(b){var d=ua.doNotTrack||ua.msDoNotTrack;(gb=b&&("yes"===d||"1"===d))&&this.disableCookies()};this.addListener=function(b,d){var f=d;"undefined"===O(f)&&(f=
!0);W(b,"click",Xa(f),!1);f&&(W(b,"mouseup",Xa(f),!1),W(b,"mousedown",Xa(f),!1),W(b,"contextmenu",Xa(f),!1))};this.enableLinkTracking=function(b){this.disableLinkTracking();"undefined"===typeof b&&(b=!0);bc=!0;U(function(){Qa(function(){Ed(b)})})};this.enableJSErrorTracking=function(b){w(b)||(b=!0);if(!cc){cc=!0;fd=b;var d=z.onerror;z.onerror=function(f,k,l,A,y){ed(f,k,l,A);return d?d(f,k,l,A,y):!1}}};this.disablePerformanceTracking=function(){Tb=!1};this.setGenerationTimeMs=function(b){Ub=parseInt(b,
10)};this.enableHeartBeatTimer=function(b){if(b){var d=uc(b);if(!d.isValid){I(d.error);return}}else b=vc;Ma.setTimings(b);gd=!0;null!==Dc&&Ma.enable()};this.disableHeartBeatTimer=function(){Ma.disable()};this.killFrame=function(){z.location!==z.top.location&&(z.top.location=z.location)};this.redirectFile=function(b){"file:"===z.location.protocol&&(z.location=b)};this.setCountPreRendered=function(b){bd=b};this.trackGoal=function(b,d,f,k){Ca(k,"trackGoal")||(k=void 0);U(function(){var l=k;l=H("idgoal="+
b+(d?"&revenue="+d:"")+"&"+ja("")+(null!==l&&void 0!==l&&l.currencyCode?"&cur="+l.currencyCode:""),f,"goal");p(l,L)})};this.trackLink=function(b,d,f,k){U(function(){ad(b,d,f,k)})};this.getNumTrackedPageViews=function(){return ob};this.trackHeartBeat=function(b){var d=!B.hasFocus||B.hasFocus();Ma.isEnabled()&&d&&(!1===Hb||!0===Ib)&&(d=ra.PeriodicHeartbeat,b.lastHeartbeat&&(d=ra.LastHeartbeat),b.blurHeartbeat&&(d=ra.BlurHeartbeat),e(d))};this.trackPageView=function(b,d,f){pa=[];dc=[];ta()?U(function(){Bd(Y,
fc,va)}):(U(function(){ob++;var k="",l;for(l=0;6>l;l++)k+="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(62*Math.random()));pb=k;k=H(ja(b),d,"log");p(k,L,f);gd&&!Ma.isEnabled()&&Ma.enable()}),1>=ob&&gc>=Math.floor(100*Math.random()+1)&&Da(function(){setTimeout(function(){var k=H("ping=5",null,"ping");p(k,L)},0)}))};this.trackAllContentImpressions=function(){ta()||U(function(){Qa(function(){var b=C.findContentNodes();b=Wa(b);u(b,L)})})};this.trackVisibleContentImpressions=
function(b,d){ta()||(w(b)||(b=!0),w(d)||(d=750),dd(b,d,this),ya||U(function(){Da(function(){var f=C.findContentNodes();f=Zb(f);u(f,L)})}))};this.trackContentImpression=function(b,d,f){ta()||(b=ba(b),d=ba(d),f=ba(f),b&&(d=d||"Unknown",U(function(){var k=Yc(b,d,f);p(k,L)})))};this.trackContentImpressionsWithinNode=function(b){!ta()&&b&&U(function(){La?Da(function(){var d=C.findContentNodesWithinNode(b);d=Zb(d);u(d,L)}):Qa(function(){var d=C.findContentNodesWithinNode(b);d=Wa(d);u(d,L)})})};this.trackContentInteraction=
function(b,d,f,k){ta()||(b=ba(b),d=ba(d),f=ba(f),k=ba(k),b&&d&&(f=f||"Unknown",U(function(){var l=rb(b,d,f,k);p(l,L)})))};this.trackContentInteractionNode=function(b,d){!ta()&&b&&U(function(){var f=Zc(b,d);p(f,L)})};this.logAllContentBlocksOnPage=function(){var b=C.findContentNodes();b=C.collectContent(b);console.log(b)};this.trackEvent=function(b,d,f,k,l,A){U(function(){$c(b,d,f,k,l,A)})};this.trackSiteSearch=function(b,d,f,k){U(function(){var l=H("search="+G(b)+(d?"&search_cats="+G(JSON.stringify(P(d)?
[d]:d)):"")+(w(f)?"&search_count="+f:""),k,"sitesearch");p(l,L)})};this.setEcommerceView=function(b,d,f,k){w(f)&&f.length?f instanceof Array&&(f=JSON.stringify(f)):f="";oa[5]=["_pkc",f];w(k)&&String(k).length&&(oa[2]=["_pkp",k]);if(w(b)&&b.length||w(d)&&d.length)w(b)&&b.length&&(oa[3]=["_pks",b]),w(d)&&d.length||(d=""),oa[4]=["_pkn",d]};this.getEcommerceItems=function(){return JSON.parse(JSON.stringify(X))};this.addEcommerceItem=function(b,d,f,k,l){b.length&&(X[b]=[b,d,f,k,l])};this.removeEcommerceItem=
function(b){b.length&&delete X[b]};this.clearEcommerceCart=function(){X={}};this.trackEcommerceOrder=function(b,d,f,k,l,A){String(b).length&&w(d)&&(Rc(Sc(),{orderId:b,grandTotal:d,subTotal:f,tax:k,shipping:l,discount:A}),X={})};this.trackEcommerceCartUpdate=function(b){Qc(Sc(),b)};this.ecommerceProductDetailView=function(b,d){Ca(d,"ecommerceProductDetailView")||(d=void 0);aa(b)&&Z("product-detail-view",b,void 0,d)};this.ecommerceAddToCart=function(b,d){Ca(d,"ecommerceAddToCart")||(d=void 0);aa(b)&&
Z("add-to-cart",b,void 0,d)};this.ecommerceRemoveFromCart=function(b,d){Ca(d,"ecommerceRemoveFromCart")||(d=void 0);aa(b)&&Z("remove-from-cart",b,void 0,d)};this.ecommerceCartUpdate=Qc;this.ecommerceOrder=Rc;this.trackError=function(b){if(b){try{var d=Gd.parse(b);var f=d[0]}catch(k){}ed(bb(b,"message"),bb(f,"fileName"),bb(f,"lineNumber"),bb(f,"columnNumber"))}};this.trackRequest=function(b,d,f,k){U(function(){var l=H(b,d,k);p(l,L,f)})};this.deanonymizeUser=function(){this.setUserIsAnonymous(0);var b=
H("ping=4",null,"ping");p(b,L)};this.getTrackingSource=function(){return[Qb,Sb]};this.setTrackingSource=function(b,d){Qb=String(b);void 0!==d&&(Sb=String(d))};this.setTrackingSourceProvider=function(b,d){"string"!==typeof b?I("[setTrackingSourceProvider]: 'provider' has to be of type string"):"string"!==typeof d?I("[setTrackingSourceProvider]: 'providerVersion' has to be of type string"):(mb=b,Rb=d)};this.getTrackingSourceProvider=function(){if(mb)return[mb,Rb]};this.setIpTracking=function(b){Lc=
b};this.setDeviceDataAnonymization=function(b){"boolean"!==typeof b?I("setDeviceDataAnonymization: The value for device data anonymization must be a boolean"):Mc=b};this.setEnableClientHints=function(b){"boolean"!==typeof b?I("[setEnableClientHints]: The value for enabling client hints must be a boolean"):Lb=b};sa.trigger("TrackerSetup",[this])}function Hd(){return{push:Pa}}function Id(a,c){var e={},g,h;for(g=0;g<c.length;g++){var n=c[g];e[n]=1;for(h=0;h<a.length;h++)if(a[h]&&a[h][0]){var m=a[h][0];
n===m&&(Pa(a[h]),delete a[h],1<e[m]&&"addTracker"!==m&&"enableLinkTracking"!==m&&I("The method "+m+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation'),e[m]++)}}Pa(["setVisitorIdCookie"]);return a}function kd(a,c){var e=new Gb(a,c);S.push(e);window._paq=Id(window._paq,Jd);for(Ea=0;Ea<window._paq.length;Ea++)window._paq[Ea]&&Pa(window._paq[Ea]);if("number"===typeof window._paq.length){var g=new Hd,h=new Date;
window._paq=g;var n=setInterval(function(){6E4<new Date-h?clearInterval(n):window._paq!==g&&(I("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."),clearInterval(n))},1E3)}else I("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/.");
return e}function Kd(a,c,e,g){function h(m){try{if(window["piwik_"+m])return window["piwik_"+m]}catch(p){}}var n=window.Piwik.getTracker(e,c);n.setDocumentTitle(a);n.setCustomData(g);(a=h("tracker_pause"))&&n.setLinkTrackingTimer(a);(a=h("download_extensions"))&&n.setDownloadExtensions(a);(a=h("hosts_alias"))&&n.setDomains(a);(a=h("ignore_classes"))&&n.setIgnoreClasses(a);n.setTimingDataSamplingOnPageLoad(0);n.trackPageView();h("install_tracker")&&(window.piwik_track=function(m,p,u,v){n.setSiteId(p);
n.setTrackerUrl(u);n.trackLink(m,v)},n.enableLinkTracking())}var kc="undefined"!==typeof globalThis?globalThis:"undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:{},vb={exports:{}},wb={exports:{}},jc;(function(a,c){(function(e,g){a.exports=g(md())})(kc,function(e){var g=/(^|@)\S+:\d+/,h=/^\s*at .*(\S+:\d+|\(native\))/m,n=/^(eval@)?(\[native code])?$/;return{parse:function(m){if("undefined"!==typeof m.stacktrace||"undefined"!==typeof m["opera#sourceloc"])return this.parseOpera(m);
if(m.stack&&m.stack.match(h))return this.parseV8OrIE(m);if(m.stack)return this.parseFFOrSafari(m);throw Error("Cannot parse given Error object");},extractLocation:function(m){if(-1===m.indexOf(":"))return[m];m=/(.+?)(?::(\d+))?(?::(\d+))?$/.exec(m.replace(/[()]/g,""));return[m[1],m[2]||void 0,m[3]||void 0]},parseV8OrIE:function(m){return m.stack.split("\n").filter(function(p){return!!p.match(h)},this).map(function(p){-1<p.indexOf("(eval ")&&(p=p.replace(/eval code/g,"eval").replace(/(\(eval at [^()]*)|(,.*$)/g,
""));var u=p.replace(/^\s+/,"").replace(/\(eval code/g,"(").replace(/^.*?\s+/,""),v=u.match(/ (\(.+\)$)/);u=v?u.replace(v[0],""):u;var r=this.extractLocation(v?v[1]:u);u=v&&u||void 0;v=-1<["eval","<anonymous>"].indexOf(r[0])?void 0:r[0];return new e({functionName:u,fileName:v,lineNumber:r[1],columnNumber:r[2],source:p})},this)},parseFFOrSafari:function(m){return m.stack.split("\n").filter(function(p){return!p.match(n)},this).map(function(p){-1<p.indexOf(" > eval")&&(p=p.replace(/ line (\d+)(?: > eval line \d+)* > eval:\d+:\d+/g,
":$1"));if(-1===p.indexOf("@")&&-1===p.indexOf(":"))return new e({functionName:p});var u=/((.*".+"[^@]*)?[^@]*)(?:@)/,v=p.match(u);v=v&&v[1]?v[1]:void 0;u=this.extractLocation(p.replace(u,""));return new e({functionName:v,fileName:u[0],lineNumber:u[1],columnNumber:u[2],source:p})},this)},parseOpera:function(m){return!m.stacktrace||-1<m.message.indexOf("\n")&&m.message.split("\n").length>m.stacktrace.split("\n").length?this.parseOpera9(m):m.stack?this.parseOpera11(m):this.parseOpera10(m)},parseOpera9:function(m){var p=
/Line (\d+).*script (?:in )?(\S+)/i;m=m.message.split("\n");for(var u=[],v=2,r=m.length;v<r;v+=2){var q=p.exec(m[v]);q&&u.push(new e({fileName:q[2],lineNumber:q[1],source:m[v]}))}return u},parseOpera10:function(m){var p=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;m=m.stacktrace.split("\n");for(var u=[],v=0,r=m.length;v<r;v+=2){var q=p.exec(m[v]);q&&u.push(new e({functionName:q[3]||void 0,fileName:q[2],lineNumber:q[1],source:m[v]}))}return u},parseOpera11:function(m){return m.stack.split("\n").filter(function(p){return!!p.match(g)&&
!p.match(/^Error created at/)},this).map(function(p){var u=p.split("@"),v=this.extractLocation(u.pop()),r=u.shift()||"";u=r.replace(/<anonymous function(: (\w+))?>/,"$2").replace(/\([^)]*\)/g,"")||void 0;var q;r.match(/\(([^)]*)\)/)&&(q=r.replace(/^[^(]+\(([^)]*)\)$/,"$1"));q=void 0===q||"[arguments not available]"===q?void 0:q.split(",");return new e({functionName:u,args:q,fileName:v[0],lineNumber:v[1],columnNumber:v[2],source:p})},this)}}})})(vb);var Gd=function(a){return a&&a.__esModule&&Object.prototype.hasOwnProperty.call(a,
"default")?a["default"]:a}(vb.exports),t={htmlCollectionToArray:function(a){var c=[],e;if(!a||!a.length)return c;for(e=0;e<a.length;e++)c.push(a[e]);return c},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return t.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var c,e=[];for(c=0;c<a.length;c++){var g=t.find(a[c]);e=e.concat(g)}return e=t.makeNodesUnique(e)},findNodesByTagName:function(a,c){if(!a||!c||!a.getElementsByTagName)return[];
var e=a.getElementsByTagName(c);return t.htmlCollectionToArray(e)},makeNodesUnique:function(a){var c=[].concat(a);a.sort(function(m,p){if(m===p)return 0;var u=ea(c,m),v=ea(c,p);return u===v?0:u>v?-1:1});if(1>=a.length)return a;var e=0,g=0,h=[],n;for(n=a[e++];n;)n===a[e]&&(g=h.push(e)),n=a[e++]||null;for(;g--;)a.splice(h[g],1);return a},getAttributeValueFromNode:function(a,c){if(t.hasNodeAttribute(a,c)){if(a&&a.getAttribute)return a.getAttribute(c);if(a&&a.attributes&&"undefined"!==O(a.attributes[c])){if(a.attributes[c].value)return a.attributes[c].value;
if(a.attributes[c].nodeValue)return a.attributes[c].nodeValue;var e,g=a.attributes;if(g){for(e=0;e<g.length;e++)if(g[e].nodeName===c)return g[e].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,c){return!!t.getAttributeValueFromNode(a,c)},hasNodeAttribute:function(a,c){return a&&a.hasAttribute?a.hasAttribute(c):a&&a.attributes?"undefined"!==O(a.attributes[c]):!1},hasNodeCssClass:function(a,c){if(a&&c&&a.className){var e="string"===typeof a.className?a.className.split(" "):[];if(-1!==
ea(e,c))return!0}return!1},findNodesHavingAttribute:function(a,c,e){e||(e=[]);if(!a||!c)return e;a=oc(a);if(!a)return e;var g;for(g=0;g<a.length;g++){var h=a[g];t.hasNodeAttribute(h,c)&&e.push(h);e=t.findNodesHavingAttribute(h,c,e)}return e},findFirstNodeHavingAttribute:function(a,c){if(a&&c){if(t.hasNodeAttribute(a,c))return a;var e=t.findNodesHavingAttribute(a,c);if(e&&e.length)return e[0]}},findFirstNodeHavingAttributeWithValue:function(a,c){if(a&&c){if(t.hasNodeAttributeWithValue(a,c))return a;
var e=t.findNodesHavingAttribute(a,c);if(e&&e.length){var g;for(g=0;g<e.length;g++)if(t.getAttributeValueFromNode(e[g],c))return e[g]}}},findNodesHavingCssClass:function(a,c,e){e||(e=[]);if(!a||!c)return e;if(a.getElementsByClassName)return c=a.getElementsByClassName(c),t.htmlCollectionToArray(c);a=oc(a);if(!a)return[];var g;for(g=0;g<a.length;g++){var h=a[g];t.hasNodeCssClass(h,c)&&e.push(h);e=t.findNodesHavingCssClass(h,c,e)}return e},findFirstNodeHavingClass:function(a,c){if(a&&c){if(t.hasNodeCssClass(a,
c))return a;var e=t.findNodesHavingCssClass(a,c);if(e&&e.length)return e[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==ea(["a","area"],a)},setAnyAttribute:function(a,c,e){a&&c&&(a.setAttribute?a.setAttribute(c,e):a[c]=e)}},pd=/^[a-z]+:\/\/.+$/i,ld={model:"ch_m",brands:"ch_b",platform:"ch_p",platformVersion:"ch_pv",fullVersionList:"ch_ufv"},Fc=function(a){var c="";if("object"===O(a))for(var e in a)if(Object.prototype.hasOwnProperty.call(a,e)&&ld[e]&&a[e]){var g=
"&".concat(ld[e],"="),h=g.concat,n;(n=a[e])?(n="object"===O(n)?JSON.stringify(n):n,n=window.encodeURIComponent(n)):n="";c+=h.call(g,n)}return c},vc=[15,30,60,120,240,480,960,1800],ra={PeriodicHeartbeat:1,LastHeartbeat:2,BlurHeartbeat:3,Deanonymize:4,PerformanceMetrics:5,OnDemand:6},Db=Object.freeze({pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",
gears:"application/x-googlegears",ag:"application/x-silverlight"}),eb,Va={},da={},B=document,ua=navigator,z=window,Pc=!1,G=z.encodeURIComponent,Fd=z.decodeURIComponent,S=[],ic=[],Ea,cb=[],C={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",
CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",CONTENT_WATCHED_ATTR:"data-content-watched",location:void 0,findContentNodes:function(){return t.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var c=t.findNodesHavingCssClass(a,this.CONTENT_CLASS),e=t.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(e&&e.length){var g;for(g=0;g<e.length;g++)c.push(e[g])}t.hasNodeAttribute(a,this.CONTENT_ATTR)?c.push(a):t.hasNodeCssClass(a,
this.CONTENT_CLASS)&&c.push(a);return c=t.makeNodesUnique(c)},findParentContentNode:function(a){if(a)for(var c=0;a&&a!==B&&a.parentNode;){if(t.hasNodeAttribute(a,this.CONTENT_ATTR)||t.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<c)break;c++}},findPieceNode:function(a){var c;(c=t.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(c=t.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return c?c:a},findTargetNodeNoDefault:function(a){if(a){var c=t.findFirstNodeHavingAttributeWithValue(a,
this.CONTENT_TARGET_ATTR);if(c||(c=t.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(c=t.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return c}},findTargetNode:function(a){var c=this.findTargetNodeNoDefault(a);return c?c:a},findTargetNodesNoDefault:function(a){if(a){var c=t.findNodesHavingAttribute(a,this.CONTENT_TARGET_ATTR);if(c&&0<c.length||(c=t.findNodesHavingCssClass(a,this.CONTENT_TARGET_CLASS))&&0<c.length)return c}},findTargetNodes:function(a){var c=C.findTargetNodesNoDefault(a);
return c&&0<c.length?c:[a]},findContentName:function(a){if(a){var c=t.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(c)return t.getAttributeValueFromNode(c,this.CONTENT_NAME_ATTR);if(c=this.findContentPiece(a))return this.removeDomainIfIsInLink(c);if(t.hasNodeAttributeWithValue(a,"title"))return t.getAttributeValueFromNode(a,"title");c=this.findPieceNode(a);if(t.hasNodeAttributeWithValue(c,"title"))return t.getAttributeValueFromNode(c,"title");a=this.findTargetNode(a);if(t.hasNodeAttributeWithValue(a,
"title"))return t.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var c=t.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(c)return t.getAttributeValueFromNode(c,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var c=this.findTargetNode(a);if(t.hasNodeAttributeWithValue(c,this.CONTENT_TARGET_ATTR))return t.getAttributeValueFromNode(c,this.CONTENT_TARGET_ATTR);
if(t.hasNodeAttributeWithValue(c,"href"))return a=t.getAttributeValueFromNode(c,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(t.hasNodeAttributeWithValue(a,"href"))return a=t.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&
((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var c=a.nodeName.toLowerCase();if(-1!==ea(["img","embed","video","audio"],c)&&t.findFirstNodeHavingAttributeWithValue(a,"src"))return a=t.findFirstNodeHavingAttributeWithValue(a,"src"),t.getAttributeValueFromNode(a,"src");if("object"===c&&t.hasNodeAttributeWithValue(a,"data"))return t.getAttributeValueFromNode(a,"data");if("object"===c){if((c=t.findNodesByTagName(a,"param"))&&c.length){var e;for(e=0;e<c.length;e++)if("movie"===
t.getAttributeValueFromNode(c[e],"name")&&t.hasNodeAttributeWithValue(c[e],"value"))return t.getAttributeValueFromNode(c[e],"value")}if((a=t.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return ba(a)},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var c=a.getBoundingClientRect(),e=B.documentElement||{},g=0>c.top;g&&a.offsetTop&&(g=0<a.offsetTop+c.height);a=e.clientWidth;z.innerWidth&&a>z.innerWidth&&(a=
z.innerWidth);e=e.clientHeight;z.innerHeight&&e>z.innerHeight&&(e=z.innerHeight);return(0<c.bottom||g)&&0<c.right&&c.left<a&&(c.top<e||g)},isNodeVisible:function(a){var c=Fb(a);a=this.isOrWasNodeInViewport(a);return c&&a},buildInteractionRequestParams:function(a,c,e,g){var h="";a&&(h+="c_i="+G(a));c&&(h&&(h+="&"),h+="c_n="+G(c));e&&(h&&(h+="&"),h+="c_p="+G(e));g&&(h&&(h+="&"),h+="c_t="+G(g));return h},buildImpressionRequestParams:function(a,c,e){a="c_n="+G(a)+"&c_p="+G(c);e&&(a+="&c_t="+G(e));return a},
buildContentBlock:function(a){if(a){var c=this.findContentName(a),e=this.findContentPiece(a);a=this.findContentTarget(a);c=this.trim(c);e=this.trim(e);a=this.trim(a);return{name:c||"Unknown",piece:e||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],e;for(e=0;e<a.length;e++){var g=this.buildContentBlock(a[e]);w(g)&&c.push(g)}return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||z.location;a.origin||(a.origin=a.protocol+
"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=
this.toAbsoluteUrl(a);if(!a)return!1;var c=this.getLocation().origin;return c===a?!0:0===String(a).indexOf(c)?":"===String(a).substr(c.length,1)?!1:!0:!1},setHrefAttribute:function(a,c){a&&c&&t.setAnyAttribute(a,"href",c)},shouldIgnoreInteraction:function(a){var c=t.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=t.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return c||a}},Jd="addTracker setTrackingSourceProvider disableCookies enableCookies setSessionIdStrictPrivacyMode setTrackerUrl setAPIUrl enableCrossDomainLinking setCrossDomainLinkingTimeout customCrossDomainLinkDecorator customCrossDomainLinkVisitorIdGetter setSecureCookie setCookiePath setCookieDomain setDomains setUserId setSiteInspectorSetup setSiteId enableLinkTracking setCustomVariableMaximumLength setDeviceDataAnonymization setEnableClientHints".split(" ");
W(z,"beforeunload",function(){for(var a=S,c=Va,e=eb,g=0;g<a.length;g+=1)a[g].trackHeartBeat({lastHeartbeat:!0});for(a=0;a<ic.length;a+=1)ic[a].trackHeartBeat({lastHeartbeat:!0});Eb(c,"unload");if(e){do c=new Date;while(c.getTime()<e)}},!1);var sa={initialized:!1,JSON:JSON,DOM:{addEventListener:function(a,c,e,g){"undefined"===O(g)&&(g=!1);W(a,c,e,g)},onLoad:Da,onReady:Qa,isNodeVisible:Fb,isOrWasNodeVisible:C.isNodeVisible},on:function(a,c){da[a]||(da[a]=[]);da[a].push(c)},off:function(a,c){if(da[a]){var e=
0;for(e;e<da[a].length;e++)da[a][e]===c&&da[a].splice(e,1)}},trigger:function(a,c,e){if(da[a]){var g=0;for(g;g<da[a].length;g++)da[a][g].apply(e||z,c)}},addPlugin:function(a,c){Va[a]=c},getTracker:function(a,c){w(c)||(c=this.getAsyncTracker().getSiteId());w(a)||(a=this.getAsyncTracker().getTrackerUrl());var e=new Gb(a,c);ic.push(e);return e},getAsyncTrackers:function(){return S},addTracker:function(a,c){return S.length?S[0].addTracker(a,c):kd(a,c)},getAsyncTracker:function(a,c){if(S&&S.length&&S[0])var e=
S[0];else return kd(a,c);if(!c&&!a)return e;w(c)&&null!==c||!e||(c=e.getSiteId());w(a)&&null!==a||!e||(a=e.getTrackerUrl());var g=0;for(g;g<S.length;g++)if((e=S[g])&&String(e.getSiteId())===String(c)&&e.getTrackerUrl()===a)return e},retryMissedPluginCalls:function(){var a=cb;cb=[];var c=0;for(c;c<a.length;c++)Pa(a[c])}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return sa});vb=sa;"object"!==O(window._paq)&&(window._paq=[]);"object"!==O(window.Piwik)&&(window.Piwik=vb);(function(){if(window&&
"object"===O(window.piwikPluginAsyncInit)&&window.piwikPluginAsyncInit.length){var a=0;for(a;a<window.piwikPluginAsyncInit.length;a++)if("function"===typeof window.piwikPluginAsyncInit[a])window.piwikPluginAsyncInit[a]()}window&&window.piwikAsyncInit&&window.piwikAsyncInit();window.Piwik.getAsyncTrackers().length?I("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."):
("object"!==O(window._paq)||"undefined"===O(window._paq.length)?0:window._paq.length)?window.Piwik.addTracker():window._paq={push:function(c){I("_paq.push() was used but Piwik tracker was not initialized before the ppms.js file was loaded. Make sure to configure the tracker via _paq.push before loading ppms.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.")}};window.Piwik.trigger("PiwikInitialized",
[]);window.Piwik.initialized=!0})();"undefined"===O(window.AnalyticsTracker)&&(window.AnalyticsTracker=window.Piwik);"function"!==typeof window.piwik_log&&(window.piwik_log=Kd)})()
//# sourceMappingURL=ppms.js.map
